### ISSUE TITLE
Text Rotation with HTML Reader

### ISSUE THREAD

**Issue by bfeduclever** [PHPOffice/PhpSpreadsheet#235]
This is:

- [ ] a bug report
- [x] a feature request
- [ ] **not** a usage question (ask them on https://stackoverflow.com/questions/tagged/phpspreadsheet or https://gitter.im/PHPOffice/PhpSpreadsheet)

### What is the expected behavior?

Have the text vertically from an attribute of a td

```html
<td alignment-textRotation="90">
```

### What is the current behavior?
The rotation is not done

### Which versions of PhpSpreadsheet and PHP are affected?
The current version : `1.0.0-beta`

**Comment by GreatHumorist** [comment]
can you describe what does this attribute do?
in excel, which function does it refer to?

**Comment by PowerKiKi** [comment]
HTML writer and reader don't support text orientation, and if they did they would have to do so via standard CSS rules, such as `style="transform: rotate(-90deg);"`, not proprietary attributes like `alignment-textRotation="90"`. Would you like to submit a patch for that ?

**Comment by GreatHumorist** [comment]
I'll add the new function later.

**Comment by GreatHumorist** [comment]
@bfeduclever 
what feature is you want?
[Transpose (rotate) data from rows to columns or vice versa](https://support.office.com/en-us/article/Transpose-rotate-data-from-rows-to-columns-or-vice-versa-3419f2e3-beab-4318-aae5-d0f862209744)
or
[Rotate or align text in a cell](https://support.office.com/en-us/article/Rotate-or-align-text-in-a-cell-8bf8177a-d2e8-4f5c-a707-d51625fd7758)

**Comment by menthol** [comment]
Hello @GreatHumorist , I work with @bfeduclever.

What we want is basically to have the ability to rotate a entire text in a cell (the second link).

In `HTML` and `CSS` they can be implemented as :
```html
<p class="vertical-rl-upright">vertical-rl-upright</p>
<p class="vertical-lr-upright">vertical-lr-upright</p>
<p class="rotation-90">rotation-90</p>
<p class="rotation-45">rotation-45</p>
<p class="rotation45">rotation45</p>
<p class="rotation90">rotation90</p>
```
```css
.vertical-rl-upright {writing-mode: vertical-rl; text-orientation: upright;}
.vertical-lr-upright {writing-mode: vertical-lr; text-orientation: upright;}
.rotation-90 {transform: rotate(-90deg);}
.rotation-45 {transform: rotate(-45deg);}
.rotation45 {transform: rotate(45deg);}
.rotation90 {transform: rotate(90deg);}
```
